<script setup lang="ts">
import { editorLayout } from '~/state/parser/parser'

const title = 'AST Explorer'
const desc = 'A web tool to explore the ASTs generated by parsers.'
const url = 'https://ast-explorer.dev/'

const ogImage = {
  url: '/og.png',
  width: 2560,
  height: 1280,
  type: 'image/png',
} as const
useSeoMeta({
  title,
  description: desc,
  ogTitle: title,
  ogDescription: desc,
  ogImage,
  ogUrl: url,
  twitterTitle: title,
  twitterDescription: desc,
  twitterImage: ogImage,
  twitterCard: 'summary_large_image',
})

useHeadSafe({
  htmlAttrs: {
    lang: 'en',
  },
  link: [
    { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg', sizes: 'any' },
  ],
})
</script>

<template>
  <ClientOnly>
    <Suspense>
      <main flex="~ col" lg:h-screen lg:w-screen>
        <Navbar v-model:layout="editorLayout" border-b />

        <div min-h-0 flex flex-1 flex-col gap2 lg:flex-row>
          <AppSideBar
            v-show="showSidebar && sideBarAvailable"
            overflow-auto
            border-r
            lg:w-75
            lg:flex-none
          />

          <Layout min-w-0 flex-1 />
        </div>
      </main>

      <template #fallback>
        <div h-screen w-screen>
          <Loading />
        </div>
      </template>
    </Suspense>
  </ClientOnly>
</template>
