<script setup lang="ts">
const title = 'AST Explorer'
const desc = 'A web tool to explore the ASTs generated by parsers.'
const url = 'https://ast-explorer.dev/'

const ogImage = {
  url: '/og.png',
  width: 2560,
  height: 1280,
  type: 'image/png',
} as const
useServerSeoMeta({
  title,
  description: desc,
  ogTitle: title,
  ogDescription: desc,
  ogImage,
  ogUrl: url,
  twitterTitle: title,
  twitterDescription: desc,
  twitterImage: ogImage,
  twitterCard: 'summary_large_image',
})

useServerHeadSafe({
  htmlAttrs: {
    lang: 'en',
  },
  link: [
    { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg', sizes: 'any' },
  ],
})

</script>

<template>
  <ClientOnly>
    <Suspense>
      <main flex="~ col" lg:h-screen>
        <Navbar v-model:layout="expLayout" border-b />

        <div min-h-0 flex flex-1 flex-col gap2 lg:flex-row>
          <AppSideBar v-show="showSidebar && sideBarAvailable" overflow-auto border-r lg:w-75 lg:flex-none />

          <SplitPane v-show="expLayout === 'layout1'" layout="vertical">
            <template #left>
              <InputContainer v-show="showInputEditor" min-w-0 h-full w-full py1 />
            </template>
            <template #right>
              <SplitPane>
                <template #left>
                  <OutputContainer :index="0" v-show="showOutput" min-w-0 h-full w-full py1 />
                </template>
                <template #right>
                  <OutputContainer :index="1" v-show="showOutput" min-w-0 h-full w-full py1 />
                </template>
              </SplitPane>
            </template>
          </SplitPane>

          <SplitPane v-show="expLayout === 'layout2'">
            <template #left>
              <InputContainer v-show="showInputEditor" min-w-0 h-full w-full py1 />
            </template>
            <template #right>
              <OutputContainer :index="0" v-show="showOutput" min-w-0 h-full w-full py1 />
            </template>
          </SplitPane>
        </div>
      </main>

      <template #fallback>
        <div h-screen w-screen>
          <Loading />
        </div>
      </template>
    </Suspense>
  </ClientOnly>
</template>
