overrides:
  vite: ^8.0.0-beta.6

catalog:
  '@astral-sh/ruff-wasm-web': ^0.14.13
  '@iconify-json/ri': ^1.2.7
  '@iconify-json/vscode-icons': ^1.2.39
  '@nuxt/kit': ^4.2.2
  '@nuxtjs/plausible': 2.0.1
  '@shikijs/monaco': ^3.21.0
  '@sxzz/eslint-config': ^7.4.5
  '@sxzz/prettier-config': ^2.2.6
  '@unocss/eslint-plugin': ^66.6.0
  '@unocss/nuxt': ^66.6.0
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  ansi-regex: ^6.2.2
  bumpp: ^10.4.0
  consola: ^3.4.2
  esbuild: ^0.27.2
  eslint: ^9.39.2
  fflate: ^0.8.2
  floating-vue: ^5.2.2
  json5: ^2.2.3
  monaco-editor: ^0.55.1
  nuxt: ^4.2.2
  nuxt-monaco-editor: ^1.4.0
  prettier: ^3.8.0
  rolldown: ^1.0.0-beta.60
  serve: ^14.2.5
  shiki: ^3.21.0
  simple-git: ^3.30.0
  typescript: ~5.9.3
  unenv: ^2.0.0-rc.24
  unocss: ^66.6.0
  unplugin-replace: ^0.6.3
  vite: ^8.0.0-beta.7
  vue: ^3.5.26
  vue-tsc: ^3.2.2

catalogs:
  parser:
    '@angular/compiler': ^21.1.0
    '@astrojs/compiler': ^2.13.0
    '@babel/parser': ^7.28.6
    '@html-eslint/parser': ^0.53.0
    '@humanwhocodes/momoa': ^3.3.10
    '@joekav/go-fast': ^0.0.5
    '@solidity-parser/parser': ^0.20.2
    '@swc/wasm-web': ^1.15.8
    '@types/css-tree': ^2.3.11
    '@types/espree': ^10.1.0
    '@types/json-to-ast': ^2.1.4
    '@typescript-eslint/parser': ^8.53.0
    '@vue-vapor/compiler-vapor': latest
    '@vue/compiler-dom': ^3.5.26
    '@vue/compiler-sfc': ^3.5.26
    acorn: ^8.15.0
    acorn-loose: ^8.5.2
    angular-html-parser: ^10.4.0
    esprima-next: ^6.0.3
    flow-parser: ^0.296.1
    graphql: ^16.12.0
    htmlparser2: ^10.0.0
    java-parser: ^3.0.1
    jinx-rust: ^0.1.6
    json-to-ast: ^2.1.0
    jsonc-eslint-parser: ^2.4.2
    lightningcss-wasm: ^1.30.2
    meriyah: ^7.0.0
    ohos-typescript: 4.9.5-r10
    oxc-parser: ^0.108.0
    php-parser: ^3.2.5
    postcss: ^8.5.6
    protobufjs: ^8.0.0
    pyodide: ^0.29.1
    rehype: ^13.0.2
    remark: ^15.0.1
    sql-parser-cst: ^0.38.2
    svelte: ^5.46.4
    ultrahtml: ^1.6.0
    web-tree-sitter: ^0.26.3
    yaml: ^2.8.2
    yaml-eslint-parser: ^2.0.0
    yaml-unist-parser: ^3.1.0

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  protobufjs: false

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
