overrides:
  '@nuxt/vite-builder': 'https://pkg.pr.new/@nuxt/vite-builder@33682'
  vite: 'catalog:'

catalog:
  '@iconify-json/ri': ^1.2.6
  '@iconify-json/vscode-icons': ^1.2.37
  '@nuxt/kit': ^4.2.1
  '@nuxtjs/plausible': 2.0.1
  '@shikijs/monaco': ^3.17.0
  '@sxzz/eslint-config': ^7.4.0
  '@sxzz/prettier-config': ^2.2.6
  '@unocss/eslint-plugin': ^66.5.10-beta.1
  '@unocss/nuxt': ^66.5.10-beta.1
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  ansi-regex: ^6.2.2
  bumpp: ^10.3.2
  consola: ^3.4.2
  esbuild: ^0.27.0
  eslint: ^9.39.1
  fflate: ^0.8.2
  floating-vue: ^5.2.2
  json5: ^2.2.3
  monaco-editor: ^0.55.1
  nuxt: ^4.2.1
  nuxt-monaco-editor: ^1.4.0
  prettier: ^3.7.3
  rolldown: ^1.0.0-beta.52
  serve: ^14.2.5
  shiki: ^3.17.0
  simple-git: ^3.30.0
  typescript: ~5.9.3
  unenv: ^2.0.0-rc.24
  unocss: ^66.5.10-beta.1
  unplugin-replace: ^0.6.2
  vite: 'npm:rolldown-vite@latest'
  vue: ^3.5.25
  vue-tsc: ^3.1.5

catalogs:
  parser:
    '@angular/compiler': ^21.0.1
    '@astrojs/compiler': ^2.13.0
    '@babel/parser': ^7.28.5
    '@html-eslint/parser': ^0.50.0
    '@humanwhocodes/momoa': ^3.3.10
    '@solidity-parser/parser': ^0.20.2
    '@swc/wasm-web': ^1.15.3
    '@types/css-tree': ^2.3.11
    '@types/espree': ^10.1.0
    '@types/json-to-ast': ^2.1.4
    '@typescript-eslint/parser': ^8.48.0
    '@vue-vapor/compiler-vapor': latest
    '@vue/compiler-dom': ^3.5.25
    '@vue/compiler-sfc': ^3.5.25
    acorn: ^8.15.0
    acorn-loose: ^8.5.2
    esprima-next: ^6.0.3
    flow-parser: ^0.291.0
    graphql: ^16.12.0
    htmlparser2: ^10.0.0
    java-parser: ^3.0.1
    jinx-rust: ^0.1.6
    json-to-ast: ^2.1.0
    jsonc-eslint-parser: ^2.4.1
    lightningcss-wasm: ^1.30.2
    meriyah: ^7.0.0
    ohos-typescript: 4.9.5-r10
    oxc-parser: ^0.99.0
    php-parser: ^3.2.5
    postcss: ^8.5.6
    rehype: ^13.0.2
    remark: ^15.0.1
    sql-parser-cst: ^0.36.1
    svelte: ^5.45.2
    ultrahtml: ^1.6.0
    yaml: ^2.8.2
    yaml-eslint-parser: ^1.3.1
