<script setup lang="ts">
import {
  SplitterGroup,
  SplitterPanel,
  SplitterResizeHandle,
  TooltipProvider,
} from 'reka-ui'

const title = 'AST Explorer'
const desc = 'A web tool to explore the ASTs generated by parsers.'
const url = 'https://ast-explorer.dev/'

const ogImage = {
  url: '/og.png',
  width: 1920,
  height: 960,
  type: 'image/png',
} as const
useSeoMeta({
  title,
  description: desc,
  ogTitle: title,
  ogDescription: desc,
  ogImage,
  ogUrl: url,
  twitterTitle: title,
  twitterDescription: desc,
  twitterImage: ogImage,
  twitterCard: 'summary_large_image',
})

useHeadSafe({
  htmlAttrs: {
    lang: 'en',
  },
  link: [
    { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg', sizes: 'any' },
  ],
})
</script>

<template>
  <ClientOnly>
    <Suspense>
      <main flex="~ col" lg:h-screen>
        <TooltipProvider
          :delay-duration="500"
          :skip-delay-duration="150"
          disable-hoverable-content
        >
          <Navbar border-b border-base />

          <div min-h-0 flex flex-1 flex-col gap0 lg:flex-row>
            <SplitterGroup
              v-if="!isMobile"
              id="ast-layout"
              class="ast-splitter"
              direction="horizontal"
            >
              <SplitterPanel
                v-if="showSidebar && sidebarAvailable"
                id="ast-layout-sidebar"
                :default-size="24"
                :order="1"
                :min-size="12"
                :max-size="40"
                class="ast-splitter-panel"
              >
                <AppSideBar h-full overflow-auto bg-elev />
              </SplitterPanel>
              <SplitterResizeHandle
                v-if="showSidebar && sidebarAvailable"
                id="ast-layout-sidebar-handle"
                class="ast-splitter-handle"
              />
              <SplitterPanel
                id="ast-layout-workspace"
                :order="2"
                class="ast-splitter-panel"
              >
                <SplitterGroup
                  id="ast-workspace-layout"
                  class="ast-splitter"
                  direction="horizontal"
                >
                  <SplitterPanel
                    v-if="showInputEditor"
                    id="ast-workspace-input"
                    :order="1"
                    :min-size="15"
                    class="ast-splitter-panel"
                  >
                    <InputContainer h-full min-w-0 py1 />
                  </SplitterPanel>
                  <SplitterResizeHandle
                    v-if="showInputEditor && showOutput"
                    id="ast-workspace-handle"
                    class="ast-splitter-handle"
                  />
                  <SplitterPanel
                    v-if="showOutput"
                    id="ast-workspace-output"
                    :order="2"
                    :min-size="15"
                    class="ast-splitter-panel"
                  >
                    <OutputContainer h-full min-w-0 py1 />
                  </SplitterPanel>
                </SplitterGroup>
              </SplitterPanel>
            </SplitterGroup>

            <template v-else>
              <AppSideBar
                v-show="showSidebar && sidebarAvailable"
                overflow-auto
                border-b
                border-base
                bg-elev
              />
              <InputContainer v-show="showInputEditor" min-w-0 flex-1 py1 />
              <div
                v-show="showInputEditor && showOutput"
                border-t
                border-base
              />
              <OutputContainer v-show="showOutput" min-w-0 flex-1 py1 />
            </template>
          </div>
        </TooltipProvider>
      </main>

      <template #fallback>
        <div h-screen w-screen>
          <Loading />
        </div>
      </template>
    </Suspense>
  </ClientOnly>
</template>
