<script setup lang="ts">
import { Pane, Splitpanes } from 'splitpanes'

const title = 'AST Explorer'
const desc = 'A web tool to explore the ASTs generated by parsers.'
const url = 'https://ast-explorer.dev/'

const ogImage = {
  url: '/og.png',
  width: 1920,
  height: 960,
  type: 'image/png',
} as const
useSeoMeta({
  title,
  description: desc,
  ogTitle: title,
  ogDescription: desc,
  ogImage,
  ogUrl: url,
  twitterTitle: title,
  twitterDescription: desc,
  twitterImage: ogImage,
  twitterCard: 'summary_large_image',
})

useHeadSafe({
  htmlAttrs: {
    lang: 'en',
  },
  link: [
    { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg', sizes: 'any' },
    { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
    {
      rel: 'preconnect',
      href: 'https://fonts.gstatic.com',
      crossorigin: 'anonymous',
    },
  ],
})
</script>

<template>
  <ClientOnly>
    <Suspense>
      <main flex="~ col" lg:h-screen>
        <Navbar border-b border-base />

        <div min-h-0 flex flex-1 flex-col gap0 lg:flex-row>
          <Splitpanes v-if="!isMobile" class="ast-splitpanes" h-full w-full>
            <Pane
              v-if="showSidebar && sideBarAvailable"
              :size="24"
              :min-size="12"
              :max-size="40"
            >
              <AppSideBar h-full overflow-auto bg-elev />
            </Pane>
            <Pane>
              <Splitpanes class="ast-splitpanes">
                <Pane v-if="showInputEditor" :min-size="15">
                  <InputContainer h-full min-w-0 py1 />
                </Pane>
                <Pane v-if="showOutput" :min-size="15">
                  <OutputContainer h-full min-w-0 py1 />
                </Pane>
              </Splitpanes>
            </Pane>
          </Splitpanes>

          <template v-else>
            <AppSideBar
              v-show="showSidebar && sideBarAvailable"
              overflow-auto
              border-b
              border-base
              bg-elev
            />
            <InputContainer v-show="showInputEditor" min-w-0 flex-1 py1 />
            <div v-show="showInputEditor && showOutput" border-t border-base />
            <OutputContainer v-show="showOutput" min-w-0 flex-1 py1 />
          </template>
        </div>
      </main>

      <template #fallback>
        <div h-screen w-screen>
          <Loading />
        </div>
      </template>
    </Suspense>
  </ClientOnly>
</template>
