name: autofix.ci

on: [pull_request]

jobs:
  autofix:
    uses: sxzz/workflows/.github/workflows/autofix.yml@main
    with:
      command: pnpm run lint --fix && pnpm run format
    permissions:
      contents: read
